BeautySouthKoreaSiteMVC/Controllers/CosmeticController.cs
using BeautySouthKoreaSiteMVC.Models;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace BeautySouthKoreaSiteMVC.Controllers
{
    public class CosmeticController : Controller
    {
        private readonly CosmeticContext db;
        public CosmeticController(CosmeticContext context)
        {
            db = context;
        }
        public async Task<IActionResult> Index()
        {
            
            return View(await db.Cosmetics.ToListAsync());
        }

        #region Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Cosmetic cosmetic)
        {
            db.Cosmetics.Add(cosmetic);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        #endregion

        #region Details
        public async Task<IActionResult> Details(int? id)
        {


            if (id != null)
            {
                Cosmetic cosmetic = await db.Cosmetics.FirstOrDefaultAsync(p => p.Id == id);
                if (cosmetic != null)
                    return View(cosmetic);
            }
            return NotFound();
        }
        #endregion

        #region Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if(id != null)
            {
                Cosmetic cosmetic = await db.Cosmetics.FirstOrDefaultAsync(p => p.Id == id);
                if (cosmetic != null)
                return View(cosmetic);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Cosmetic cosmetic)
        {
            db.Cosmetics.Update(cosmetic);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        #endregion

        #region Delete
        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if(id != null)
            {
                Cosmetic cosmetic = await db.Cosmetics.FirstOrDefaultAsync(p => p.Id == id);
                if (cosmetic != null)
                    return View(cosmetic);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if(id !=null)
            {
                Cosmetic cosmetic = await db.Cosmetics.FirstOrDefaultAsync(p => p.Id == id);
                if(cosmetic != null)
                {
                    db.Cosmetics.Remove(cosmetic);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return NotFound();
        }
        #endregion

        public async Task<IActionResult> Product(int? id)
        {
            if (id != null)
                {
                    Cosmetic cosmetic = await db.Cosmetics.FirstOrDefaultAsync(p => p.Id == id);
                    if (cosmetic != null)
                        return View(cosmetic);
            }
            return NotFound();
        }

        #region PartialView
        public ActionResult Goods()
        {
            return PartialView("_Goods");
        }

        public ActionResult InputFilter()
        {
            return PartialView("_inputFilter");
        }

        #endregion

        public IActionResult Face(string[] color, string[] brand, string[] PurposeFor, string sortOrder)
        {

            ViewBag.color = color;
            ViewBag.PurposeFor = PurposeFor;
            ViewBag.brand = brand;
            ViewBag.NameSortParm = string.IsNullOrEmpty(sortOrder) ? "Name_desc" : "";
            ViewBag.PriceSortParm = sortOrder == "Price" ? "Price_desc" : "Price";

            var cosmetics = db.Cosmetics.Where(c => c.PurposeFor.Contains("Face")).ToList();
            var co_cars = new List<Cosmetic>();
            var ma_cars = new List<Cosmetic>();
            var purposeFor = new List<Cosmetic>();


            if (color.Length != 0)
            {
                foreach (string co in color)
                {
                    var colorfiltercars = db.Cosmetics.Where(c => c.Color.Contains(co)).ToList();
                    co_cars.AddRange(colorfiltercars);
                }
            }
            else
            {
                co_cars = cosmetics;
            }

            if (PurposeFor.Length != 0)
            {
                foreach (string pf in PurposeFor)
                {
                    var purposefiltercars = db.Cosmetics.Where(c => c.PurposeFor.Contains(pf)).ToList();
                    purposeFor.AddRange(purposefiltercars);
                }
            }
            else
            {
                purposeFor = cosmetics;
            }

            if (brand.Length != 0)
            {
                foreach (string ma in brand)
                {
                    var manufacturerfiltercars = db.Cosmetics.Where(c => c.Brand.Contains(ma)).ToList();
                    ma_cars.AddRange(manufacturerfiltercars);
                }
            }
            else
            {
                ma_cars = cosmetics;
            }

            var filtercars = co_cars.Intersect(ma_cars);
            filtercars = filtercars.Intersect(purposeFor);

            switch (sortOrder)
            {
                case "Name_desc":
                    filtercars = filtercars.OrderByDescending(s => s.Name);
                    break;
                case "Price":
                    filtercars = filtercars.OrderBy(s => s.Price);
                    break;
                case "Price_desc":
                    filtercars = filtercars.OrderByDescending(s => s.Price);
                    break;
                default:
                    filtercars = filtercars.OrderBy(s => s.Name);
                    break;
            }
            return View(filtercars.ToList());
        }

        public IActionResult Eyes()
        {
            var cosmetics = from s in db.Cosmetics select s;
            cosmetics = cosmetics.Where(c => c.PurposeFor.Contains("Eyes"));
            return View(cosmetics);
        }
        public IActionResult Lips()
        {
            var cosmetics = from s in db.Cosmetics select s;
            cosmetics = cosmetics.Where(c => c.PurposeFor.Contains("Lips"));
            return View(cosmetics);
        }
        public IActionResult Fingernails()
        {
            var cosmetics = from s in db.Cosmetics select s;
            cosmetics = cosmetics.Where(c => c.PurposeFor.Contains("Fingernails"));
            return View(cosmetics);
        }
        public IActionResult RemovingMakeup()
        {
            var cosmetics = from s in db.Cosmetics select s;
            cosmetics = cosmetics.Where(c => c.PurposeFor.Contains("RemovingMakeup"));
            return View(cosmetics);
        }
    }
}

BeautySouthKoreaSiteMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BeautySouthKoreaSiteMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Data.SqlClient;

namespace BeautySouthKoreaSiteMVC.Controllers
{
    public class HomeController : Controller
    {

        private readonly CosmeticContext db;
        public HomeController(CosmeticContext context)
        {
            db = context;
        }

        public IActionResult Index(string[] color, string[] brand, string[] PurposeFor, string search, string sortOrder)
        {
            
            ViewBag.color = color;
            ViewBag.PurposeFor = PurposeFor;
            ViewBag.brand = brand;
            ViewBag.search = search;
            ViewBag.NameSortParm = string.IsNullOrEmpty(sortOrder) ? "Name_desc" : "";
            ViewBag.PriceSortParm = sortOrder == "Price" ? "Price_desc" : "Price";

            var cosmetics = db.Cosmetics.ToList();
            var co_cars = new List<Cosmetic>();
            var ma_cars = new List<Cosmetic>();
            var purposeFor = new List<Cosmetic>();
            var schStr = new List<Cosmetic>();

            if (!string.IsNullOrEmpty(search))
            {
                    var sr = db.Cosmetics.Where(c => c.Name.Contains(search)).ToList();
                    schStr.AddRange(sr);
            }
            else
            {
                schStr = cosmetics;
            }

            if (color.Length != 0)
            {
                foreach (string co in color)
                {
                    var colorfiltercars = db.Cosmetics.Where(c => c.Color.Contains(co)).ToList();
                    co_cars.AddRange(colorfiltercars);
                }
            }
            else
            {
                co_cars = cosmetics;
            }

            if (PurposeFor.Length != 0)
            {
                foreach (string pf in PurposeFor)
                {
                    var purposefiltercars = db.Cosmetics.Where(c => c.PurposeFor.Contains(pf)).ToList();
                    purposeFor.AddRange(purposefiltercars);
                }
            }
            else    
            {
                purposeFor = cosmetics;
            }

            if (brand.Length != 0)
            {
                foreach (string ma in brand)
                {
                    var manufacturerfiltercars = db.Cosmetics.Where(c => c.Brand.Contains(ma)).ToList();
                    ma_cars.AddRange(manufacturerfiltercars);
                }
            }
            else
            {
                ma_cars = cosmetics;
            }

            var filtercars = co_cars.Intersect(ma_cars);
            filtercars = filtercars.Intersect(purposeFor);
            filtercars = filtercars.Intersect(schStr);
           
            switch (sortOrder)
            {
                case "Name_desc":
                    filtercars = filtercars.OrderByDescending(s => s.Name);
                    break;
                case "Price":
                    filtercars = filtercars.OrderBy(s => s.Price);
                    break;
                case "Price_desc":
                    filtercars = filtercars.OrderByDescending(s => s.Price);
                    break;
                default:
                    filtercars = filtercars.OrderBy(s => s.Name);
                    break;
            }
            return View(filtercars.ToList());
        }
      

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BeautySouthKoreaSiteMVC/Views/Home/Index.cshtml
@model IEnumerable<BeautySouthKoreaSiteMVC.Models.Cosmetic>
@{
    ViewData["Title"] = "BSK";


}

<div class="container">
    <div class="content row">
        <div class="col-sm-3">
            <section class="sticky-top">

                <div class="col-md-12 p-0 m-0" type="button" data-toggle="collapse" data-target="#collapseFace" aria-expanded="false" aria-controls="collapseExample">
                    <div class="border-bottom border-top f-sz-18">
                        <a href="Cosmetic/Face" class="text-decoration-none text-dark">Face</a>
                    </div>
                </div>
                <div class="collapse" id="collapseFace">
                    <div>
                        <div><a class="text-decoration-none text-dark f-sz-15 ml-3" href="#">Тональное средство</a></div>
                        <div><a class="text-decoration-none text-dark f-sz-15 ml-3" href="#">ВВ-крем</a></div>
                        <div><a class="text-decoration-none text-dark f-sz-15 ml-3" href="#">СС-Крем</a></div>
                        <div><a class="text-decoration-none text-dark f-sz-15 ml-3" href="#">Румяна</a></div>
                        <div><a class="text-decoration-none text-dark f-sz-15 ml-3" href="#">Контуринг лица</a></div>
                        <div><a class="text-decoration-none text-dark f-sz-15 ml-3" href="#">Бронзеры</a></div>
                        <div><a class="text-decoration-none text-dark f-sz-15 ml-3" href="#">Хайлайтеры</a></div>
                        <div><a class="text-decoration-none text-dark f-sz-15 ml-3" href="#">Пудры</a></div>
                        <div><a class="text-decoration-none text-dark f-sz-15 ml-3" href="#">Консилеры, корректоры</a></div>
                        <div><a class="text-decoration-none text-dark f-sz-15 ml-3" href="#">Базы, праймеры под макияж</a></div>
                        <div><a class="text-decoration-none text-dark f-sz-15 ml-3" href="#">Спреи для фиксации макияжа</a></div>
                    </div>
                </div>

                <p class="col-md-12">
                    <div type="button" data-toggle="collapse" data-target="#collapseEye" aria-expanded="false" aria-controls="collapseExample">
                        <div class="border-bottom border-top f-sz-18">

                            <a href="Cosmetic/Eyes" class="text-decoration-none text-dark">Eye</a>

                        </div>
                    </div>
                </p>
                <div class="collapse" id="collapseEye">
                    <div class="card card-body">
                        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.
                    </div>
                </div>

                <p>
                    <div type="button" data-toggle="collapse" data-target="#collapseNails" aria-expanded="false" aria-controls="collapseExample">
                        <div class="border-bottom border-top f-sz-18">
                            <a href="Cosmetic/Fingernails" class="text-decoration-none text-dark">Fingernails</a>
                        </div>
                    </div>
                </p>
                <div class="collapse" id="collapseNails">
                    <div class="card card-body">
                        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.
                    </div>
                </div>

                <p>
                    <div type="button" data-toggle="collapse" data-target="#collapseLips" aria-expanded="false" aria-controls="collapseExample">
                        <div class="border-bottom border-top f-sz-18">
                            <a href="Cosmetic/Lips" class="text-decoration-none text-dark">Lips</a>
                        </div>
                    </div>
                </p>
                <div class="collapse" id="collapseLips">
                    <div class="card card-body">
                        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.
                    </div>
                </div>

                <p>
                    <div type="button" data-toggle="collapse" data-target="#collapseMakeupRemoval" aria-expanded="false" aria-controls="collapseExample">
                        <div class="border-bottom border-top f-sz-18">
                            <a href="Cosmetic/RemovingMakeup" class="text-decoration-none text-dark">Removing makeup</a>
                        </div>
                    </div>
                </p>
                <div class="collapse" id="collapseMakeupRemoval">
                    <div class="card card-body">
                        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.
                    </div>
                </div>

            </section>
        </div>

        <div class="col-sm-9 p-0">
            <div class="col-md-12 mb-3">
                <form id="my_form" asp-action="Index" method="get">
                    <label>Color:</label>
                    <input type="checkbox" name="color" value="black" /><span>Black</span>
                    <input type="checkbox" name="color" value="white" /><span>White</span>
                    <br />
                    <p></p>
                    <label>Manufacturer:</label>
                    <input type="checkbox" name="brand" value="A" /><span>A</span>
                    <input type="checkbox" name="brand" value="B" /><span>B</span>
                    <input type="checkbox" name="brand" value="C" /><span>C</span>
                    <input type="checkbox" name="brand" value="D" /><span>D</span>
                    <p></p>
                    <label>Purpose:</label>
                    <input type="checkbox" name="PurposeFor" value="SS" /><span>Лица</span>
                    <input type="checkbox" name="PurposeFor" value="Глаз" /><span>Глаз</span>
                    <input type="checkbox" name="PurposeFor" value="Ногтей" /><span>Ногтей</span>
                    <input type="checkbox" name="PurposeFor" value="Губ" /><span>Губ</span>

                    <input class="btn btn-info float-right" type="submit" value="Search" />
                </form>

                <table class="table">
                    <thread>
                        <tr>
                            <th>
                                <a class="sort" id="sortname" data-sortorder="@ViewBag.NameSortParm" href="javascript:void(0)">@Html.DisplayNameFor(model => model.Name)</a>
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Color)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Brand)
                            </th>
                            <th>
                                <a class="sort" id="sortprice" data-sortorder="@ViewBag.PriceSortParm" href="javascript:void(0)">@Html.DisplayNameFor(model => model.Price)</a>
                            </th>
                        </tr>
                    </thread>
                </table>
            </div>




           
                


                    <div class="row pr-3 pl-3">
                        @foreach (var c in Model)
                        {
                            if (c.ShowMainScreen == true)
                            {
                                <div class="filter col-md-3 p-0 hover-bc-card" data-category="@c.PurposeFor">
                                    <div class="p-3">
                                        <a class="text-decoration-none text-dark" asp-action="Product" asp-controller="Cosmetic" asp-route-id="@c.Id">
                                            <div>
                                                <img class="card-img-top p-4 bg-white" src=@c.Img alt="@c.Name">
                                            </div>
                                        </a>
                                        <div class="card-body">
                                            <h5 class="card-title text-center">@c.Name</h5>
                                            <p class="card-text text-center f-sz-12 ">@c.PurposeFor</p>
                                            <p class="card-text rounded text-center price-for-list">@c.Price ₴</p>
                                        </div>
                                    </div>
                                </div>
                            }
                        }
                    </div>
        </div>
    </div>
</div>
@section scripts{
    <script>
        var color = @Html.Raw(Json.Serialize(ViewBag.color));
        var brand = @Html.Raw(Json.Serialize(ViewBag.brand));
        var PurposeFor = @Html.Raw(Json.Serialize(ViewBag.PurposeFor));

        $(function () {
            var checkoptions = [];
            checkoptions = brand;
            checkoptions = color;
            checkoptions = PurposeFor;
            $('input[type=checkbox]').each(function () {
                if (checkoptions.includes(this.value)) {
                    $(this).prop("checked", true);
                }
            });
        })


        $(".sort").click(function () {
            var sortorder = $(this).data('sortorder');
            var link = "/Home/Index?";
            color.forEach(function (value) {
                link += "color=" + value + "&";
            });
            brand.forEach(function (value) {
                link += "manufacturer=" + value + "&";
            });
            link += "sortOrder=" + sortorder;
            window.location.href = link;
        })


        $("a").click(function (event) {
            event.stopPropagation();
        });
    </script>
}